# Generated by Django 2.1.7 on 2019-10-20 02:31

from django.db import migrations, models
import interface_main.models.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('interface_main', '0002_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='mock的名称')),
                ('description', models.CharField(default='', max_length=2000, verbose_name='mock的描述')),
                ('method', models.CharField(default='get', max_length=20, verbose_name='方法')),
                ('response', interface_main.models.fields.json_field.JsonField(verbose_name='响应')),
            ],
        ),
    ]
