# Generated by Django 2.1.7 on 2019-11-03 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_main', '0003_mock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='mock的名称')),
                ('description', models.CharField(default='', max_length=2000, verbose_name='mock的描述')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInterfaceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface_main.Interface')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface_main.Task')),
            ],
        ),
    ]
