# Generated by Django 2.1.7 on 2019-11-10 02:27

from django.db import migrations, models
import django.db.models.deletion
import interface_main.models.fields.json_field


class Migration(migrations.Migration):

    dependencies = [
        ('interface_main', '0004_task_taskinterfacerelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='代表成功或者失败')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='代表创建时间')),
                ('version', models.IntegerField(default=1, verbose_name='代表某一次的执行的版本')),
                ('request', interface_main.models.fields.json_field.JsonField(verbose_name='参数')),
                ('response', models.TextField(default='', verbose_name='响应')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface_main.Task')),
            ],
        ),
    ]
